from parsers import santafe, santafe_id, maine, minneapolis, sf, sfnoid, old, prm, burlington
from functools import partial
competitions = [
    {
        'office': 'Mayor',  
        'date': '2018', 
        'place' : 'Santa Fe',
        'path': 'Ballot_Images/Santa_Fe/csvFiles/CvrExport.csv',
        'parser': partial(santafe,0,1),
        'idparser': partial(santafe_id,0,1)
    },
    {
        'office': 'Councilor District 4',  
        'date': '2018', 
        'place' : 'Santa Fe',
        'path': 'Ballot_Images/Santa_Fe/csvFiles/CvrExport.csv',
        'parser': partial(santafe,1,5),
        'idparser': partial(santafe_id,1,5)
    },
    {
        'office': 'Councilor District 2',  
        'date': '2018', 
        'place' : 'Santa Fe',
        'path': 'Ballot_Images/Santa_Fe/csvFiles/CvrExport.csv',
        'parser': partial(santafe,1,3),
        'idparser': partial(santafe_id,1,3)
    },
    {
        'office': 'Democratic Primary for CD2',  
        'date': '2018', 
        'place': 'Maine',
        'path': 'Ballot_Images/Maine/csvMaine/Maine_Democratic_Primary_for_CD2_CVR.xlsx.csv',
        'parser': partial(maine,5),
        'write_ins': 1
    },
    {
        'office': 'Democratic Primary for Governor',  
        'date': '2018', 
        'place': 'Maine',
        'path': 'Ballot_Images/Maine/csvMaine/Maine Democratic Primary for Governor CVR.xlsx.csv',
        'parser': partial(maine,8),
        'write_ins': 1
    },
    {
        'office': 'General CD2',  
        'date': '2018', 
        'place': 'Maine',
        'path': 'Ballot_Images/Maine/csvMaine/Maine General CD2 CVR Updated.xlsx.csv',
        'parser': partial(maine,5),
        'write_ins': 1
    },
    {
        'office': 'Mayor',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-mayor-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'BOE',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-boe-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park At Large', 
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-park-at-large-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 1',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-park-district-1-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {   
        'office': 'Park District 2', 
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-park-district-2-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 3', 
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-park-district-3-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {   
        'office': 'Park District 4',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-park-district-4-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {   'office': 'Park District 5',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-park-district-5-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 6',
        'date': '2017',
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-park-district-6-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {   
        'office': 'Ward 1',
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-1-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 2',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-2-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 3',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-3-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 4',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-4-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 5',  
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-5-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 6',
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-6-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 7',
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-7-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 8', 
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-8-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {   
        'office': 'Ward 9',
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-9-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 10',
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-10-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 11',
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-11-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 12',
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-12-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 13',
        'date': '2017', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2017/csv2017/2017-ward-13-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Mayor',
        'date': '2013', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2013_only those contested/csv2013/Minneapolis 2013-mayor-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'BOE',
        'date': '2013', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2013_only those contested/csv2013/Minneapolis 2013-board of estimation and taxation cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park At Large',
        'date': '2013', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2013_only those contested/csv2013/Minneapolis 2013-park-at-large-cvr.xlsx.csv',
        'parser': minneapolis,
        'number': 3,
    },
    {   
        'office': 'Park District 2',  
        'date': '2013', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2013_only those contested/csv2013/Minneapolis 2013-park-district-2-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 6', 
        'date': '2013', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2013_only those contested/csv2013/Minneapolis 2013-park-district-6-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 5',  
        'date': '2013', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2013_only those contested/csv2013/Minneapolis 2013 Council - ward-5-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 9',
        'date': '2013', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2013_only those contested/csv2013/Minneapolis 2013 Council - ward-9-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {   
        'office': 'Ward 13',
        'date': '2013', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2013_only those contested/csv2013/Minneapolis 2013 Council - ward-13-cvr.xlsx.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Mayor',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Mayor.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'BOE', 
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Board of Estimate and Taxation – At-Large – elect 2.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park At Large',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Park and Recreation Board – At-Large – elect 3.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 1',  
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis Park and Recreation Board District 1.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 2',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis Park and Recreation Board District 2.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 3', 
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis Park and Recreation Board District 3.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 4',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis Park and Recreation Board District 4.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 5',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis Park and Recreation Board District 5.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Park District 6',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis Park and Recreation Board District 6.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 1',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 1.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 2',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 2.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 3',  
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 3.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 4',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 4.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 5',  
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 5.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 6',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 6.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 7',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 7.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 8',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 8.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 9',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 9.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 10',  
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 10.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 11',  
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 11.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 12',  
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 12.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Ward 13',
        'date': '2009', 
        'place': 'Minneapolis',
        'path': 'Ballot_Images/Minneapolis/2009/csv2009/Minneapolis 2009 Council Member Ward 13.xls.csv',
        'parser': minneapolis,
    },
    {
        'office': 'Mayor',  
        'date': '2015', 
        'place': 'San Francisco',
    # do not compare with https://sfelections.org/results/20151103/
    # compare with https://sfelections.org/results/20151103/data/20151119/mayor/20151119_mayor.html
        'path': 'Ballot_Images/San Francisco/2015 All offices/20151119_ballotimage.txt',
        'parser': partial(sf,'0000001'),
    }, 
    {
        'office': 'Sheriff',
        'date': '2015', 
        'place': 'San Francisco',
    # see note under 'San Francisco Mayor 2015'
        'path': 'Ballot_Images/San Francisco/2015 All offices/20151119_ballotimage.txt',
        'parser': partial(sf,'0000002'),
    }, 
    {
        'office': 'Board of Supervisors District 3',  
        'date': '2015', 
        'place': 'San Francisco',
    # see note under 'San Francisco Mayor 2015'
        'path': 'Ballot_Images/San Francisco/2015 All offices/20151119_ballotimage.txt',
        'parser': partial(sf,'0000003'),
    },
    {
        'office': 'Assessor-Recorder',  
        'date': '2018', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_assessor_ballotimage.txt',
        'parser': sfnoid,
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_masterlookup.txt'
    },
    {
        'office': 'Public Defender',  
        'date': '2018', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_defender_ballotimage.txt',
        'parser': sfnoid,
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_masterlookup.txt'
    },
    {
        'office': 'Board of Supervisors District 2',  
        'date': '2018', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_d2_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_masterlookup.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 4',  
        'date': '2018', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_d4_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_masterlookup.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 6',  
        'date': '2018', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_d6_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_masterlookup.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 8',  
        'date': '2018', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_d8_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_masterlookup.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 10',  
        'date': '2018', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_d10_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2018/20181127_masterlookup.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 1',  
        'date': '2016', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_masterlookup.txt',
        'parser': partial(sf,'0000009'),
    },
    {
        'office': 'Board of Supervisors District 3',  
        'date': '2016', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_masterlookup.txt',
        'parser': partial(sf,'0000010'),
    },
    {
        'office': 'Board of Supervisors District 5',  
        'date': '2016', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_masterlookup.txt',
        'parser': partial(sf,'0000011'),
    },
    {
        'office': 'Board of Supervisors District 7',  
        'date': '2016', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_masterlookup.txt',
        'parser': partial(sf,'0000012'),
    },
    {
        'office': 'Board of Supervisors District 9',
        'date': '2016', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_masterlookup.txt',
        'parser': partial(sf,'0000013'),
    },
    {
        'office': 'Board of Supervisors District 11',
        'date': '2016', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_ballotimage.txt',
        'master_lookup': 'Ballot_Images/San Francisco/San Fran_Nov 2016/20161206_masterlookup.txt',
        'parser': partial(sf,'0000014'),
    },
    {
        'office': 'Board of Supervisors District 10',  
        'date': '2014', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2014_District 10 Supervisors/D10_BallotImage.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 7',  
        'date': '2012', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2012_District 7 Supervisors/D7-BallotImage.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 5',  
        'date': '2012', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2012_District 5 Supervisors/D5-BallotImage.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 10',  
        'date': '2010', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2010_District 10 Supervisors/BallotImage-D10.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 8',  
        'date': '2010', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2010_District 8 Supervisors/BallotImage-D8.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 6',  
        'date': '2010', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2010_District 6 Supervisors/BallotImage-D6.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 2',  
        'date': '2010', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2010_District 2 Supervisors/BallotImage-D2.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Board of Supervisors District 1',  
        'date': '2008', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2008_All District races/CityWide_BallotImage.txt',
        'parser': partial(sf,'0000003'),
    },
    {
        'office': 'Board of Supervisors District 3',  
        'date': '2008', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2008_All District races/CityWide_BallotImage.txt',
        'parser': partial(sf,'0000005'),
    },
    {
        'office': 'Board of Supervisors District 4',  
        'date': '2008', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2008_All District races/CityWide_BallotImage.txt',
        'parser': partial(sf,'0000006'),
    },
    {
        'office': 'Board of Supervisors District 5',  
        'date': '2008', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2008_All District races/CityWide_BallotImage.txt',
        'parser': partial(sf,'0000007'),
    },
    {
        'office': 'Board of Supervisors District 7',  
        'date': '2008', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2008_All District races/CityWide_BallotImage.txt',
        'parser': partial(sf,'0000008'),
    },
    {
        'office': 'Board of Supervisors District 9',  
        'date': '2008', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2008_All District races/CityWide_BallotImage.txt',
        'parser': partial(sf,'0000009'),
    },
    {
        'office': 'Board of Supervisors District 11',  
        'date': '2008', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran_Nov 2008_All District races/CityWide_BallotImage.txt',
        'parser': partial(sf,'0000004'),
    },
    {
        'office': 'Sheriff',  
        'date': '2011', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran Nov 2011 Sheriff/Sheriff-BallotImage.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Mayor',  
        'date': '2011', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran Nov 2011 Mayor/Mayor-BallotImage.txt',
        'parser': sfnoid,
    },
    {
        'office': 'District Attorney',  
        'date': '2011', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran Nov 2011 District Attorney/DA-BallotImage.txt',
        'parser': sfnoid,
    },
    {
        'office': 'District 1',  
        'date': '2004', 
        'place': 'San Francisco',
        #https://sfelections.sfgov.org/rcv-district-1-nov-2004
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D01-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D01-Cntl.txt',
    },
    {
        'office': 'District 2',  
        'date': '2004', 
        'place': 'San Francisco',
        #values infered from ballot data, not documented here https://sfelections.sfgov.org/results-summary-nov-2004
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D02-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D02-Cntl.txt',
    },
    {
        'office': 'District 3',  
        'date': '2004', 
        'place': 'San Francisco',
        #values infered from ballot data, not documented here https://sfelections.sfgov.org/results-summary-nov-2004
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D03-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D03-Cntl.txt',
    },
    {
        'office': 'District 5',  
        'date': '2004', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D05-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D05-Cntl.txt',
    },
    {
        'office': 'District 7',  
        'date': '2004', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D07-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D07-Cntl.txt',
    },
    {
        'office': 'District 9',  
        'date': '2004', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D09-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D09-Cntl.txt',
    },
    {
        'office': 'District 11', 
        'date': '2004', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D11-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2004/D11-Cntl.txt',
    },
    {
        'office': 'Mayor',  
        'date': '2018', 
        'place': 'San Francisco',
        #https://sfelections.org/results/20180605/data/20180627/mayor/20180627_mayor.html
        'path': 'Ballot_Images/San Francisco/San Fran June 2018/20180621_ballotimage.txt',
        'parser': partial(sf,'0000020'),
    },
    {
        'office': 'Board of Supervisors District 8',  
        'date': '2018', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/San Fran June 2018/20180621_ballotimage.txt',
        'parser': partial(sf,'0000021'),
    },
    {
        'office': 'Mayor',
        'date': '2007', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2007/MYR-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2007/MYR-Cntl.txt',
    },
    {
        'office': 'Board of Supervisors District 2',  
        'date': '2006', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D02-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D02-Cntl.txt',
    },
    {
        'office': 'Board of Supervisors District 4',  
        'date': '2006', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D04-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D04-Cntl.txt', 
    },
    {
        'office': 'Board of Supervisors District 6',  
        'date': '2006', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D06-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D06-Cntl.txt',
    },
    {
        'office': 'Board of Supervisors District 8',  
        'date': '2006', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D08-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D08-Cntl.txt',
    },
    {
        'office': 'Board of Supervisors District 10',  
        'date': '2006', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D10-Ballots.txt',
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2006/D10-Cntl.txt',
        'parser': old,
    },
    {
        'office': 'Treasurer',  
        'date': '2005', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2005/TR-Ballots.txt',
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2005/TR-Cntl.txt',
        'parser': old,
    },
    {
        'office': 'Assessor-Recorder',  
        'date': '2005', 
        'place': 'San Francisco',
        'path': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2005/AR-Ballots.txt',
        'parser': old,
        'candidate_map': 'Ballot_Images/San Francisco/RCVCalc Ballot Images/2005/AR-Cntl.txt',
    },
    {
        'office': 'Executive',  
        'date': '2008', 
        'place': 'Pierce County',
        'path': 'Ballot_Images/Pierce County/Pierce County Executive 2008 Ballot Image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council District 2',  
        'date': '2008', 
        'place': 'Pierce County',
        'path': 'Ballot_Images/Pierce County/Pierce County Council, District No. 2 2008 Ballot Image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Auditor',  
        'date': '2009', 
        'place': 'Pierce County',
        'path': 'Ballot_Images/Pierce County/Pierce County Auditor 2009 Ballot Image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Assessor - Treasurer',  
        'date': '2008', 
        'place': 'Pierce County',
        'path': 'Ballot_Images/Pierce County/Pierce County Assessor - Treasurer 2008 Ballot Image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'City Attorney',  
        'date': '2012', 
        'place': 'Oakland',
         'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_City Attorney - Oakland_Nov 2012.txt',
         'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 3',  
        'date': '2012', 
        'place': 'Berkeley',
         'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 3 - Berkeley_Nov 2012.txt',
         'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 7',  'date': '2012', 'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 7- Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 5',  
        'date': '2012', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 5- Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 6',  
        'date': '2012', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 6 - San Leandro_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council At-Large',  
        'date': '2012', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, At-Large - Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 1',  
        'date': '2012', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 1- Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 3',  
        'date': '2012', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council,District 3 - Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 3',  
        'date': '2012', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_School Director, District 3 - Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 6',  
        'date': '2012', 
        'place': 'Berkeley',
         'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 6 - Berkeley_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 2',  
        'date': '2012', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 2 - Berkeley_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 2',  
        'date': '2012', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 2 - San Leandro_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 7',  
        'date': '2012', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_School Director, District 7 - Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Mayor',  
        'date': '2012', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Mayor - Berkeley_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 1',  
        'date': '2012', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_School Director, District 1 - Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 5',  
        'date': '2012', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_School Director, District 5 - Oakland_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 4',  
        'date': '2012', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 4 - San Leandro_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 5',  
        'date': '2012', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2012/ballot_image_Member, City Council, District 5 - Berkeley_Nov 2012.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 6',  
        'date': '2014', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 6 - Oakland_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 7',  
        'date': '2014', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 7 - Berkeley_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 8',  
        'date': '2014', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 8 - Berkeley_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 1',  
        'date': '2014', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 1 - San Leandro_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 2',  
        'date': '2014', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 2 - Oakland_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'City Auditor',  
        'date': '2014', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_City Auditor - Oakland_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 4',  
        'date': '2014', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 4 - Oakland_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Mayor',  
        'date': '2014', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Mayor of San Leandro_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Mayor',  
        'date': '2014', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Mayor - Oakland_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'City Auditor',  
        'date': '2014', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_City Auditor - Berkeley_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 5',  
        'date': '2014', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 5 - San Leandro_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 4',  'date': '2014', 'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_School Director, District 4 - Oakland_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 1',  
        'date': '2014', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 1 - Berkeley_Nov_2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 2',  
        'date': '2014', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_School Director, District 2 - Oakland_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 3',  
        'date': '2014', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_Member, City Council, District 3 - San Leandro_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 6',  
        'date': '2014', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2014/ballot_image_School Director, District 6 - Oakland_Nov 2014.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD3',  
        'date': '2016', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/BerkeleyCouncilD3/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD2',  
        'date': '2016', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/BerkeleyCouncilD2/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD5',  
        'date': '2016', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/BerkeleyCouncilD5/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'SchoolD1',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandSchoolD1/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD7',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandCouncilD7/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Mayor',  
        'date': '2016', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/BerkeleyMayor/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD1',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandCouncilD1/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'SchoolD7',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandSchoolD7/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD2',  
        'date': '2016', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/SanLeandroCouncilD2/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD4',  
        'date': '2016', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/SanLeandroCouncilD4/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD6',  
        'date': '2016', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/BerkeleyCouncilD6/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'SchoolD5',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandSchoolD5/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD3',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandCouncilD3/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD5',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandCouncilD5/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'SchoolD3',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandSchoolD3/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilAtLrg',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandCouncilAtLrg/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Attorney',  
        'date': '2016', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/OaklandAttorney/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD6',  
        'date': '2016', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2016/SanLeandroCouncilD6/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 4',  
        'date': '2010', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 4 - Oakland_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 2',  
        'date': '2010', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 2 - Oakland_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 1',  
        'date': '2010', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 1 - San Leandro_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 8',  
        'date': '2010', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 8 - Berkeley_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 7',  
        'date': '2010', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 7 - Berkeley_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 6',  
        'date': '2010', 'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 6 - Oakland_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 4',  
        'date': '2010', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 4 - Berkeley_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'City Auditor',  
        'date': '2010', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_City Auditor - Oakland_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 5',  
        'date': '2010', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 5 - San Leandro_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Mayor',  
        'date': '2010', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Mayor of San Leandro_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'City Auditor',  
        'date': '2010', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_City Auditor - Berkeley_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 6',  
        'date': '2010', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_School Director, District 6 - Oakland_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Mayor',  
        'date': '2010', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Mayor of Oakland_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 1',  
        'date': '2010', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 1 - Berkeley_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 4',  
        'date': '2010', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_School Director, District 4 - Oakland_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Director District 2',  
        'date': '2010', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_School Director, District 2 - Oakland_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Member City Council District 3',  
        'date': '2010', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2010/ballot_image_Member, City Council, District 3 - San Leandro_Nov 2010.txt',
        'parser': sfnoid,
    },
    {
        'office': 'CouncilD4',  
        'date': '2017', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda (Oakland, San Leandro, Berkeley) 2017/BerkCouncilD4/ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School Committee',  
        'date': '2017', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2017/2017/School Committee/*.prm',
        'parser': prm,
        'chp': 'Ballot_Images/Cambridge/2017/2017/School Committee/school 2017 FINAL Order Test.chp',
    },
    {
        'office': 'City Council',  
        'date': '2017', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2017/2017/City Council/*.prm',
        'parser': prm,
        'chp': 'Ballot_Images/Cambridge/2017/2017/City Council/council 2017 FINAL Order Test.chp',
    },
    {
        'office': 'School Committee',  
        'date': '2015', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2015/school2015/*.prm',
        'parser': prm,
        'chp': 'Ballot_Images/Cambridge/2015/school2015/*.chp',
    },
    {
        'office': 'City Council',  
        'date': '2015', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2015/council2015/*.prm',
        'chp': 'Ballot_Images/Cambridge/2015/council2015/*.chp',
        'parser': prm,
    },
    {
        'office': 'School Committee',  
        'date': '2013', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2013/School/*/*.PRM',
        'chp': 'Ballot_Images/Cambridge/2013/School/*/*.chp',
        'parser': prm,
    },
    {
        'office': 'City Council',  
        'date': '2013', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2013/Council/*/*.PRM',
        'chp': 'Ballot_Images/Cambridge/2013/Council/*/*.chp',
        'parser': prm,
    },
    {
        'office': 'School Committee',  
        'date': '2011', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2011/School/*/*.PRM',
        'parser': prm,
        'chp': 'Ballot_Images/Cambridge/2011/School/Final/School Final Piles Report.txt',
    }, 
    {
        'office': 'City Council',  
        'date': '2011', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2011/Council/*/*.PRM',
        'parser': prm,
        'chp': 'Ballot_Images/Cambridge/2011/Council/Final/Council Final Piles Report.txt',
    },
    ### Doesn't match with results here https://www.cambridgema.gov/~/media/Files/electioncommission/SchoolCommittee_results.pdf?la=en
    #'Cambridge School Committee 2009': {'office': '#School Committee',  'date': '2009', 'place': 'Cambridge',
    #    'path': 'Ballot_Images/Cambridge/2009/School/*/*.PRM',
    #    'parser': prm,
    #}, 
    {
        'office': 'City Council',  
        'date': '2009', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2009/Council/*/*.PRM',
        'chp': 'Ballot_Images/Cambridge/2009/Council/Final/*.chp',
        'parser': prm,
    }, 
    {
        'office': 'City Council',  
        'date': '2007', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2007/Council/*/*.[pP][rR][mM]',
        'chp': 'Ballot_Images/Cambridge/2007/Council/*/*.chp',
        'parser': prm,
    }, 
    {
        'office': 'School Committee',  
        'date': '2007', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2007/School/*/*.[pP][rR][mM]',
        'chp': 'Ballot_Images/Cambridge/2007/School/*/*.chp',
        'parser': prm,
    }, 
    {
        'office': 'School Committee',  
        'date': '2005', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2005/School/*/*.[pP][rR][mM]',
        'chp': 'Ballot_Images/Cambridge/2005/School/*/*.chp',
        'parser': prm,
    }, 
    {
        'office': 'City Council',  
        'date': '2005', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2005/Council/*/*.[pP][rR][mM]',
        'chp': 'Ballot_Images/Cambridge/2005/Council/*/*.chp',
        'parser': prm,
    }, 
    {
        'office': 'City Council',  
        'date': '2003', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2003/Council/*/*.[pPW][rRE][mMD]',
        'chp': 'Ballot_Images/Cambridge/2003/Council/*/*.chp',
        'parser': prm,
    }, 
    {
        'office': 'School Committee',  
        'date': '2003', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2003/School/*/*.[pPW][rRE][mMD]',
        'chp': 'Ballot_Images/Cambridge/2003/School/school.chp', 
        'parser': prm,
    }, 
    {
        'office': 'City Council',  
        'date': '2001', 
        'place': 'Cambridge',
        'path': 'Ballot_Images/Cambridge/2001/Council - Wednesday/*.PRM',
        'chp': 'Ballot_Images/Cambridge/2001/Council - Wednesday/*.chp',
        'parser': prm,
    }, 
    {
        'office': 'Mayor',
        'date': '2006',
        'place': 'Burlington',
        'path': 'Ballot_Images/Burlington/Burlington Mayor 2006.txt',
        'parser': burlington,
    },
    {
        'office': 'Mayor', 
        'date': '2009', 
        'place': 'Burlington',
        'path': 'Ballot_Images/Burlington/2009 Burlington Mayor/*.PRM',
        'chp': 'Ballot_Images/Burlington/2009 Burlington Mayor/*.chp',
        'parser': prm,
    },
    {
        'office': 'Mayor',  
        'date': '2018', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/SanLeandroMayor2018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D5',  
        'date': '2018', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/SanLeandroCouncilD52018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D3',  
        'date': '2018', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/SanLeandroCouncilD32018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D1',  
        'date': '2018', 
        'place': 'San Leandro',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/SanLeandroCouncilD12018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School D6',  
        'date': '2018', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/OaklandSchoolD62018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School D4',  
        'date': '2018', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/OaklandSchoolD42018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'School D2',  
        'date': '2018', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/OaklandSchoolD22018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D6',  
        'date': '2018', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/OaklandCouncilD62018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D4',  
        'date': '2018', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/OaklandCouncilD42018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D2',  
        'date': '2018', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/OaklandCouncilD22018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Mayor',  
        'date': '2018', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/OaklandMayor2018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'City Auditor',  
        'date': '2018', 
        'place': 'Oakland',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/OaklandCityAuditor2018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D8',  
        'date': '2018', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/BerkeleyCouncilD82018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D7',  
        'date': '2018', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/BerkeleyCouncilD72018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D4',  
        'date': '2018', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/BerkeleyCouncilD42018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'Council D1',  
        'date': '2018', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/BerkeleyCouncilD12018ballot_image.txt',
        'parser': sfnoid,
    },
    {
        'office': 'City Auditor',  
        'date': '2018', 
        'place': 'Berkeley',
        'path': 'Ballot_Images/Alameda (Oakland, San Leandro, Berkeley)/Alameda2018/BerkeleyCityAuditor2018ballot_image.txt',
        'parser': sfnoid,
    }
}
 
